services:
  minecraft-service:
    image: itzg/minecraft-server:java25-graalvm
    container_name: fabric-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "25565:25565"
      - "25565:25565/udp"
      - "24454:24454/udp"
      - "${TS_IP}:25585:25585" # fabricexporter
    environment:
      EULA: true
      TYPE: FABRIC

      # VERSION_FROM_MODRINTH_PROJECTS: true # dynamically set VERSION if all modrinth projects support latest version
      MOTD: "%TYPE% server running §l§cMinecraft§r §n%VERSION%.\ Aka A §g§lminecraft§r §u-.-§r §5§mServer§r made by §a§kkaktus"
      ICON: "/icon.png"
      OVERRIDE_ICON: true
      LEVEL: "world"
      ONLINE_MODE: true

      MAX_PLAYERS: "20"
      DIFFICULTY: HARD
      MODE: "SURVIVAL"
      PVP: "TRUE"

      VIEW_DISTANCE: 12
      SPAWN_PROTECTION: 0
      SIMULATION_DISTANCE: 10

      EXISTING_OPS_FILE: "SYNCHRONIZE"
      OPS: "${MC_OPS}"
      EXISTING_WHITELIST_FILE: "SYNCHRONIZE"
      WHITELIST: "${MC_WHITELIST}"
      ENFORCE_WHITELIST: true
      ENABLE_WHITELIST: true

      RCON_PASSWORD: ${RCON_PASSWORD}

      USE_MEOWICE_FLAGS: true
      USE_MEOWICE_GRAALVM_FLAGS: true
      MEMORY: 5G
      JVM_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders" # not in meowice yet

      REMOVE_OLD_MODS: false
      VANILLATWEAKS_SHARECODE: SNoKz9
      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: BETA
      MODRINTH_DOWNLOAD_DEPENDENCIES: REQUIRED
      MODRINTH_PROJECTS: |

        fabric-api
        fabric-language-kotlin
        fabricexporter
        fabric-permissions-api

        spark
        ferrite-core
        krypton
        lithium
        scalablelux
        c2me-fabric
        entityculling

        packet-fixer
        alternate-current
        chunky
        clumps
        zfastnoise
        servercore
        no-chat-reports
        view-distance-fix
        servux
        tabtps
        # achievements-optimizer
        # architectury-api
        # tt20

        luckperms
        vanish
        bluemap
        carpet
        # worldedit
        # axiom
        simple-voice-chat
        #plasmo-voice # TODO: migrate from svc
        appleskin
        netherportalfix
        balm # netherportalfix dep

      RCON_CMDS_STARTUP: |-
        gamerule players_sleeping_percentage 0
        carpet setDefault optimizedTNT true
        carpet setDefault maxFakePlayers 3
        carpet commandPlayer true
        lp group default permission set tabtps.tps true
        lp group default permission set tabtps.ping true
        lp group default permission set tabtps.defaultdisplay true
        lp group default permission set tabtps.toggle true
        lp group default permission set tabtps.toggle.tab true
        lp group default permission set tabtps.toggle.actionbar true
        lp group default permission set tabtps.toggle.bossbar true
        lp creategroup carpet_trusted
        lp group carpet_trusted permission set carpet.commands.player true
        lp group carpet_trusted parent add default
    volumes:
      - ./static/icon.png:/icon.png
      - ./data/minecraft:/data

      # TODO: add declarative mc mod configs
      # # Luckperms config
      # - ./mc/luckperms/luckperms.conf:/data/config/luckperms/luckperms.conf:ro
      # - ./mc/luckperms/groups:/data/config/luckperms/yaml-storage/groups
      # # Carpet config
      # - ./mc/carpet.conf:/data/config/carpet.conf:ro
    healthcheck:
      test: ["CMD", "mc-health"]
      interval: 1m
      timeout: 20s
      retries: 15
      start_period: 2m
    deploy:
      resources:
        limits:
          memory: 6.5G
    networks:
      minecraft-network:
        aliases:
          - mc-server

  backup:
    image: itzg/mc-backup
    container_name: mc-backup
    hostname: mc-backup-worker
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      INITIAL_DELAY: 1m
      BACKUP_INTERVAL: 1h
      RCON_HOST: minecraft-service
      RCON_PASSWORD: "${RCON_PASSWORD}"

      # Compression & Size Savings (exclude bluemap)
      EXCLUDES: "bluemap,logs,cache,emotes,*.tmp,web,*.map"

      PRUNE_RESTIC_RETENTION: "--keep-within 24h --keep-daily 7 --keep-weekly 4 --keep-monthly 6"
      BACKUP_METHOD: "restic"
      RESTIC_REPOSITORY: "s3:${R2_ENDPOINT}/${R2_BUCKET_NAME}"
      RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
      AWS_ACCESS_KEY_ID: "${R2_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${R2_SECRET_ACCESS_KEY}"
      RESTIC_OPTS: "-o s3.connections=10 -o s3.region=auto --compression auto"
    volumes:
      - ./data/minecraft:/data:ro
      # - ./rclone:/config/rclone
    depends_on:
      minecraft-service:
        condition: service_healthy
    networks:
      minecraft-network:
        aliases:
          - mc-backup

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "${TS_IP}:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    networks:
      minecraft-network:
        aliases:
          - grafana

  # Collect metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    ports:
      - "${TS_IP}:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      minecraft-network:
        aliases:
          - prometheus

  # Collect logs
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "${TS_IP}:3100:3100"
    # command: "-config.file=/etc/loki/local-config.yaml"
    volumes:
      # - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      minecraft-network:
        aliases:
          - loki

  # Telemetry pipeline (forward data to loki/prometheus)
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "${TS_IP}:12345:12345"
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--storage.path=/var/lib/alloy/data",
        "/etc/alloy/config.alloy",
      ]
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      # Mount the rootless socket & logs
      - /var/run/docker.sock:/var/run/docker.sock
      - alloy_data:/var/lib/alloy/data

      # Mount to interal host/ to not mess with container's own system metrics
      - /:/host/rootfs:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /run/udev/data:/host/run/udev/data:ro

      # Mount minecraft logs
      # - ./data/minecraft/logs:/var/log/minecraft:ro
    networks:
      minecraft-network:
        aliases:
          - alloy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "${TS_IP}:9000:9000"
    volumes:
      # Map the docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      minecraft-network:
        aliases:
          - portainer

networks:
  minecraft-network:
    name: minecraft
    # external: true

volumes:
  grafana_data:
  prometheus_data:
  loki_data:
  alloy_data:
  portainer_data:
