apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-main
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      timeInterval: 15s
    editable: false

  - name: Loki
    type: loki
    uid: loki-main
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    editable: false
