{
 "title": "Minecraft Logging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User activity",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"minecraft\", job=\"minecraft\"} |= `joined the game`"
    },
    {
     "direction": "backward",
     "expr": "{service_name=\"minecraft\", job=\"minecraft\"} |= `left the game`"
    }
   ]
  },
  {
   "title": "Whitelist",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"minecraft\", job=\"minecraft\"} |= `to the whitelist`"
    },
    {
     "direction": "backward",
     "expr": "{service_name=\"minecraft\", job=\"minecraft\"} |= `from the whitelist`"
    }
   ]
  },
  {
   "title": "Server Console",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"fabric-server_logs\", job=\"fabric-server_logs\"}"
    }
   ]
  }
 ]
}